formatter: "markdown table"

version: ">= 0.16.0"

recursive:
  enabled: false
  path: modules

sections:
  hide: []
  show: []

content: |-
  # Terraform NDFC Fabric Module

  **NOTICE:** *This module is under active development, the first fabric template to be included is the easy_fabric, additional templates will be added in the future.*

  A Terraform module to create and update a fabric in NDFC. Due to the structure of the NDFC API delete or destory operations are not permitted. The goal is to allow the creation of the fabric as part of a Infrastructure as Code workflow. 
  Using a YAML document with the needed elements a fabric can be configured. 

  ## Usage
  By providing a directory of YAML files that define the configurations for the fabric settings are merged with the defaults to simplify the definitions required.
  Users need only to define the fabric settings that they require and all other NDFC fabric template defaults are applied.

  To see all available options the defaults for each fabric type are included in the defaults directory within the module repo [rjohnston6/terraform-dcnm-ndfc-fabric](https://github.com/rjohnston6/terraform-dcnm-ndfc-fabric/tree/main/defaults). Only the options that deviate from the defaults need to be declared.

  ## Examples
  ### New Easy Fabric
  Example Directory structure for project
  {{ include "./examples/easy_fabric/directory-structure.md" }}

  Configure a new Easy Fabric based fabric.

  #### 'fabric.yaml'

  ```hcl
  {{ include "./examples/easy_fabric/data/fabric.yaml" }}
  ```

  #### 'main.tf'

  ```hcl
  {{ include "./examples/easy_fabric/main.tf" }}
  ```

  ## Acknowledgements

  The module leverages efforts made by [Daniel Schmidt](https://github.com/danischm) and his Nexus-as-Code repo based for ACI [netascode/terraform-aci-nac-aci](https://github.com/netascode/terraform-aci-nac-aci). His work of using YAML as a data source and merging with default configurations streamlined and accelerated the capability to develop this NDFC module.
    
  {{ .Requirements }}

  {{ .Inputs }}

  {{ .Providers }}

  {{ .Resources }}

output:
  file: "README.md"
  mode: replace

sort:
  enabled: true
  by: required

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
